image : mcr.microsoft.com/dotnet/sdk:5.0

stages:
  - build
  - release

build:
  stage: build
  script:
    - dotnet build

release:
  stage: release
  only:
    - master
  artifacts:
    paths:
      - publish/
  script:
    - dotnet publish -c Release -p:PublishSingleFile=true --self-contained true -p:IncludeNativeLibrariesForSelfExtract=true -o ../publish MarshmallowPortal.Client/MarshmallowPortal.Client.csproj
    - dotnet publish -c Release -p:PublishSingleFile=true --self-contained true -p:IncludeNativeLibrariesForSelfExtract=true -o ../publish MarshmallowPortal.Server/MarshmallowPortal.Server.csproj